[project]
name = 'mentormatch-ai'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.mentor-match]
path = 'contracts/mentor-match.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
